---
podSpec:
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
  priorityClassName: system-node-critical
  volumes:
    - name: shared
      emptyDir: {}
sonobuoy-config:
  driver: Job
  plugin-name: 99-openshift-artifacts-collector
  result-format: raw
  description: |
    OPCT artifacts plugin collects the artifacts from the OpenShift Container
    Platform post-validation.
  source-url:
    "https://github.com/redhat-openshift-ecosystem/provider-certification-tool/\
    blob/main/manifests/openshift-artifacts-collector.yaml"
  skipCleanup: true
spec:
  name: plugin
  image: "quay.io/opct/plugin-artifacts-collector:v0.0.0-devel-f17e7fa"
  imagePullPolicy: Always
  command: ["/bin/bash", "/plugin/entrypoint-collector.sh"]
  volumeMounts:
    - mountPath: /tmp/shared
      name: shared
  env:
    - name: PLUGIN_ID
      value: "99"
    - name: PLUGIN_NAME
      value: "openshift-artifacts-collector"
    - name: PLUGIN_BLOCKED_BY
      value: ""
    - name: IMAGE_OVERRIDE_MUST_GATHER
      value: "quay.io/opct/must-gather-monitoring:devel"
    - name: ENV_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: ENV_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: ENV_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: RUN_MODE
      value: "default"
    - name: SKIP_MUST_GATHER
      value: "true"
    - name: SKIP_PERFORMANCE
      value: "true"
    - name: SKIP_METRICS
      value: "true"
