# Base image
FROM registry.access.redhat.com/ubi8/ubi-minimal:latest as ubi-base
RUN microdnf install yum \
  && yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical

# Layering Tools image
FROM quay.io/ocp-cert/tools:v0.0.0-oc41018-s0565 as tools

# Plugin container image
FROM ubi-base
LABEL io.k8s.display-name="OpenShift Tests for Provider Certification Plugin" \
      io.k8s.description="OpenShift is a platform for developing, building, and deploying containerized applications." \
      io.openshift.tags="openshift,tests,e2e,partner,certification,plugin"
COPY --from=tools /usr/bin/sonobuoy /usr/bin/
COPY --from=tools /usr/bin/oc /usr/bin/
COPY --from=tools /usr/bin/jq /usr/bin/

#TODO: embeed the nc on tools layer (build it statically)
RUN yum clean all \
  && microdnf clean all

RUN ln -svf /usr/bin/oc /usr/bin/kubectl

WORKDIR /plugin

COPY ./tests ./tests
COPY ./plugin/*.sh ./

CMD ["./runner.sh"]
