#
# ATTENTION: The Containerfile was created automatically from hack/Containerfile.alp
#

# Plugin container image
FROM ${CONTAINER_TOOLS}
LABEL io.k8s.display-name="OpenShift Tests for Provider Certification Plugin" \
      io.k8s.description="OpenShift is a platform for developing, building, and deploying containerized applications." \
      io.openshift.tags="openshift,tests,e2e,partner,certification,plugin"
WORKDIR /plugin

COPY ./tests ./tests
COPY ./plugin/*.sh ./
COPY ./VERSION ./

CMD ["./runner.sh"]
