
ARG TOOLS_IMG=quay.io/opct/tools:v0.2.0
FROM --platform=$TARGETPLATFORM ${TOOLS_IMG} AS build

ARG QUAY_EXPIRATION=never
ARG TARGETARCH
ARG TARGETPLATFORM
ARG TARGETOS
LABEL io.k8s.display-name="OPCT Must-Gather Monitoring" \
      io.k8s.description="Collect Prometheus raw metrics from OpenShift/OCP Clusters." \
      io.openshift.tags="openshift,monitoring,must-gather,opct" \
      quay.expires-after=${QUAY_EXPIRATION} \
      architecture=$TARGETARCH \
      platform=$TARGETPLATFORM \
      os=$TARGETOS

# For gathering data from nodes
RUN microdnf update -y && \
    microdnf install util-linux rsync -y && \
    microdnf clean all

COPY ./VERSION .

# Copy all collection scripts to /usr/bin
COPY collection-scripts/* /usr/bin/

# runner_plugin is used when the Must-gather is called as a sonobuoy plugin
COPY runner_plugin /usr/bin/

RUN chmod u+x /usr/bin/gather* /usr/bin/runner_plugin

ENTRYPOINT /usr/bin/gather