
#
## Base image for must-gather-monitoring plugin
#
FROM quay.io/opct/tools:v0.4.0 as tools

FROM quay.io/fedora/fedora-minimal:40 as base
ARG QUAY_EXPIRATION=never
LABEL io.k8s.display-name="OPCT Must-Gather Monitoring" \
      io.k8s.description="Collect Prometheus raw metrics from OpenShift/OCP Clusters." \
      io.openshift.tags="openshift,monitoring,must-gather,opct" \
      quay.expires-after=${QUAY_EXPIRATION}

WORKDIR /plugin
RUN echo "fastestmirror=true" >> /etc/dnf/dnf.conf \
    && microdnf install -y curl grep tar xz gzip rsync util-linux \
    && microdnf clean all

COPY --from=tools /usr/bin/oc /usr/bin/oc

# Copy all collection scripts to /usr/bin
COPY collection-scripts/* /usr/bin/

# runner_plugin is used when the Must-gather is called as a sonobuoy plugin
COPY runner_plugin /usr/bin/

RUN chmod u+x /usr/bin/gather* /usr/bin/runner_plugin

ENTRYPOINT /usr/bin/gather
