FROM quay.io/opct/tools:v0.4.0

ARG QUAY_EXPIRATION=never
ARG TARGETARCH
ARG TARGETPLATFORM
ARG TARGETOS

LABEL io.k8s.display-name="OPCT Plugin openshift-tests" \
      io.k8s.description="OPCT Plugin openshift-tests runs conformance tests using OpenShift e2e suites." \
      io.openshift.tags="opct,plugin,openshift,okd,tests,e2e" \
      quay.expires-after=${QUAY_EXPIRATION} \
      architecture=$TARGETARCH \
      platform=$TARGETPLATFORM \
      os=$TARGETOS

WORKDIR /plugin
COPY ./plugin/*.sh ./

CMD ["./runner.sh"]
