#
# Tools image is used to handle the utilities used in the plugins, such as
# oc, jq, camgi.
#

#
## Base image
#
FROM quay.io/fedora/fedora-minimal:41 as base
RUN echo "fastestmirror=true" >> /etc/dnf/dnf.conf && \
    microdnf install -y curl grep tar xz gzip && \
    microdnf clean all

FROM base as clients
WORKDIR /clients
ARG JQ_URL=TBD
ARG JQ_BIN=TBD
ARG CAMGI_URL=TBD
ARG CAMGI_TAR=TBD
ARG OC_URL=TBD
ARG OC_TAR=TBD

ADD ${OC_URL} ./
ADD ${JQ_URL} ./
ADD ${CAMGI_URL} ./
RUN microdnf install -y binutils \
    && tar xvfz ${OC_TAR} \
    && rm -f ${OC_TAR} kubectl README.md \
    && tar xvf ${CAMGI_TAR} && rm ${CAMGI_TAR} \
    && chmod +x ${JQ_BIN} oc camgi \
    && strip oc && strip camgi \
    && mv ${JQ_BIN} jq \
    && microdnf clean all

#
## Tools image
#
FROM base
ARG QUAY_EXPIRATION=never
ARG TARGETARCH
ARG TARGETPLATFORM
ARG TARGETOS
LABEL io.k8s.display-name="OPCT Tools" \
      io.k8s.description="Tools is the intermediary image handling utilities used by OPCT plugins." \
      io.openshift.tags="opct,openshift,tests,e2e,provider,conformance,tools" \
      quay.expires-after=${QUAY_EXPIRATION} \
      architecture=$TARGETARCH \
      platform=$TARGETPLATFORM \
      os=$TARGETOS

WORKDIR /tools
ARG SONOBUOY_VERSION=TBD
COPY --from=clients /clients/oc /usr/bin/oc
COPY --from=clients /clients/jq /usr/bin/jq
COPY --from=clients /clients/camgi /usr/bin/camgi

RUN ln -svf /usr/bin/oc /usr/bin/kubectl
