#
# Go Builder image: openshift-tests plugin
#
FROM docker.io/golang:1.21-alpine AS gobuilder
ARG RELEASE_TAG
RUN apk add --no-cache --update make git
WORKDIR /go/src/github.com/redhat-openshift-ecosystem/provider-certification-plugins/openshift-tests-plugin
RUN rm ./openshift-tests-plugin || true
COPY . .
RUN go build . && mv ./openshift-tests-plugin /openshift-tests-plugin

FROM quay.io/fedora/fedora-minimal:39
WORKDIR /opct

COPY --from=gobuilder /openshift-tests-plugin /usr/bin/

CMD [ "/usr/bin/openshift-tests-plugin" ]
