---
name: reviewer

on:
  workflow_call: {}

# golangci-lint-action requires those permissions to annotate issues in the PR.
permissions:
  contents: read
  checks: write
  issues: read
  pull-requests: write

env:
  GO_VERSION: 1.23
  GOLANGCI_LINT_VERSION: v1.59

jobs:
  # https://github.com/reviewdog/action-misspell
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-misspell@v1
        with:
          # reporter: github-check
          # level: warning
          locale: "US"

  # reviewdog / suggester: https://github.com/reviewdog/action-suggester
  go_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gofmt -w -s .
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt
